const bookData = [
  {
    id: 1,
    title: "The Art of Code",
    author: "Ada Lovelace",
    price: 14.99,
    category: "Programming",
    language: "English",
    published: "2022-08-12",
  },
  {
    id: 2,
    title: "Digital Nomad Diaries",
    author: "Linus Roam",
    price: 9.5,
    category: "Lifestyle",
    language: "English",
    published: "2021-11-02",
  },
  {
    id: 3,
    title: "Pixel & Pen",
    author: "Clara Byte",
    price: 19.0,
    category: "Design",
    language: "English",
    published: "2023-01-17",
  },
  {
    id: 4,
    title: "Node.js for Humans",
    author: "James Syntax",
    price: 11.75,
    category: "Programming",
    language: "English",
    published: "2020-05-29",
  },
  {
    id: 5,
    title: "React Realities",
    author: "Sophie JSX",
    price: 16.49,
    category: "Web Development",
    language: "English",
    published: "2023-03-08",
  },
  {
    id: 6,
    title: "Express Lane",
    author: "Morgan Route",
    price: 12.25,
    category: "Backend",
    language: "English",
    published: "2021-09-19",
  },
  {
    id: 7,
    title: "Tailwind Vision",
    author: "Sadaf Shahab",
    price: 18.0,
    category: "CSS Frameworks",
    language: "English",
    published: "2024-02-22",
  },
  {
    id: 8,
    title: "MERN Manifesto",
    author: "Aarav Tech",
    price: 21.99,
    category: "Full Stack",
    language: "English",
    published: "2025-01-15",
  },
];

export { bookData };
